language: c

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6-dev

install:
  - mkdir _build
  - cd _build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=$(pwd)/../_inst
  - make install

script:
  - ctest
