%YAML 1.2
---
run_duration:
  description: Simulation run time
  value:
    type: float
    default: 30.0
    units: d
    range:
      min: 1
      max: 1000000
---
number_of_rows:
  name: Number of rows
  description: Number of grid rows
  value:
    type: int
    default: 50
    range:
      min: 7
      max: 2147483647
    units: -

number_of_columns:
  name: Number of columns
  description: Number of grid columns
  value:
    type: int
    default: 50
    range:
      min: 7
      max: 2147483647
    units: -

grid_spacing_row:
  name: Grid row spacing
  description: Grid resolution in northerly (row) direction
  value:
    type: float
    default: 10000.0
    range:
      min: 1.0
      max: 1.79769e308
    units: -

grid_spacing_col:
  name: Grid column spacing
  description: Grid resolution in easterly (column) direction
  value:
    type: float
    default: 10000.0
    range:
      min: 1.0
      max: 1.79769e308
    units: -

center_row_node:
  name: Row node of center
  description: Grid row of storm center
  value:
    type: int
    default: 25
    range:
      min: 1
      max: 2147483647
    units: -

center_col_node:
  name: Column node of center
  description: Grid column of storm center
  value:
    type: int
    default: 25
    range:
      min: 1
      max: 2147483647
    units: -
---
storm_speed:
  name: Storm speed
  description: Propagation speed of storm
  value:
    type: float
    default: 5.0
    range:
      min: 0.0
      max: 1.79769e308
    units: m/s

storm_direction:
  name: Storm direction
  description: Direction of storm propagation (CCW from east)
  value:
    type: float
    default: 180.0
    range:
      min: 0.0
      max: 360.0
    units: deg

pressure_center:
  name: Central pressure
  description: Atmospheric pressure at center of storm
  value:
    type: float
    default: 99800.0
    range:
      min: 0.0
      max: 1.79769e308
    units: Pa

pressure_edge:
  name: Edge pressure
  description: Atmospheric pressure at edge of storm
  value:
    type: float
    default: 101300.0
    range:
      min: 0.0
      max: 1.79769e308
    units: Pa

storm_radius:
  name: Storm radius
  description: Radius of storm
  value:
    type: float
    default: 1.0e6
    range:
      min: 0.0
      max: 1.79769e308
    units: m

radius_of_maximum_winds:
  name: Radius of maximum winds
  description: Radius of maximum storm winds
  value:
    type: float
    default: 24400.0
    range:
      min: 0.0
      max: 1.79769e308
    units: m
